name: InventoryExchanger
main: InventoryExchanger\matcracker\Main
version: 2.0.0
api: [1.13.0]
author: matcracker

commands:
 inventoryexchanger:
  permission: inventoryexchanger.command.inve
  description: For change inventory and save the old in the same world.
  usage: /inventoryexchanger
  aliases: [inve, inventorye, invexchange]

permissions:
 inventoryexchanger.command.inve:
  default: true
  description: For change inventory and save the old in the same world.