name: InventoryExchanger
main: InventoryExchanger\matcracker\Main
version: 2.0.0
api: [1.13.0]
author: matcracker

commands:
 inve:
  permission: inventoryexchanger.command.inve
  description: InventoryExchanger Command
  usage: /inve

permissions:
 inventoryexchanger.command:
  default: op
  description: InventoryExchanger Plugin by matcracker
  children:
   inventoryexchanger.command.inve:
    default: true
    description: For change inventory and save the old in the same world.