#Configuration file for InventoryExchanger 2.4
#Language part
message-command: "&2You correctly change inventory!"
message-console: "&cPlease run this command in-game"
message-no-permission: "&4You don't have permission to use this command!"
message-no-drop: "&cYou can't drop items in this world!"
message-death-drop: "&cYou are dead but your drops have been cancelled in this world!"

#Enable or disable prefix when running commands
enable-prefix: true

#Enable or disable drops on some worlds
enable-drop: true
#If enable-drop is false, you can choose on which worlds the drops are disabled
#If enable-drop is true, you can choose on which worlds the drops are enabled
worlds-drop:
  - world
  - world2

enable-death-drop: false
#If enable-death-drop is false, you can choose on which worlds the drops of player are disabled
#If enable-death-drop is true, you can choose on which worlds the drops of player are enabled
worlds-death-drop:
  - world
  - world2

#Enable for share the same invetory in other worlds
enable-shared-worlds: false
#Choose which worlds you can share the same inventory.
worlds-shared-inventory:
 - world2
 - world3